### ISSUE TITLE
EXE installer didn't do anything with custom install location.

### ISSUE THREAD

**Issue by Gaboris** [babgozd/camporter96-custom#18]
I installed Steam on my D: drive and had my Beta operational since day one.

I had Steam turned off and even though AVG stopped the installer at first I've set it as an exception and ran it again.
The Command line menu said that the installation was successful, but restarting Steam didn't change anything and even checking the folders there was no grid folder created in config.

Did I mess up something or does the installer not account for custom install locations?

BTW I've already manually "installed" the images from the Google Drive so I'm really just asking in case this is an actual problem.

**Comment by djandDK** [comment]
It currently doesn't handle custom locations, give me a second to fix that.

**Comment by djandDK** [comment]
@Gaboris can i get you to test this one?: https://github.com/djandDK/camporter96-custom/blob/master/CustomGrids.exe

**Comment by Gaboris** [comment]
YEP! This one worked just fine!

I guess detecting a custom installation location isn't as straight forward as one would hope to, but if people don't mess up their laths then this should be just fine. :)

Thanks for the quick fix.

**Comment by djandDK** [comment]
Well i might be able to find the path somewhere but i currently don't know where to get it. I might look into it later, but this will work as a fix in the meantime.

**Comment by Gaboris** [comment]
OH! One more thing:
Can I keep using this EXE for future updates, or are images directly addressed within it  and wouldn't notice new pics in the repository?
Also what if new pics come along and I don't want to download all the ones I already have? Does this installer check for duplicated first?

**Comment by djandDK** [comment]
>
>
> Can I keep using this EXE for future updates, or are images directly addressed within it and wouldn't notice new pics in the repository?

You can use this one as long as the images doesn't get moved to a different folder in the github directory.

> 
> 
> Also what if new pics come along and I don't want to download all the ones I already have? Does this installer check for duplicated first?

It checks whether a file with the same name already exists locally, if the file exists it doesn't download anything and goes on to check if the next file exists.
