### ISSUE TITLE
Should we add all the artwork to a folder, to keep the repo clear?

### ISSUE THREAD

**Issue by hannes-dev** [babgozd/camporter96-custom#2]
Maybe we can put all the .png files in a folder called 'artwork' or something, so the repo is clear, and the readme can be scrolled to easily?

Also, maybe make all the folders lowercase, for easier navigation in a command line, but this can be up for debate.

**Comment by babgozd** [comment]
That would be nicer also right now I am planning to add easier to install one zip file contains all of artworks named with corresponding appid. Someone on reddit post already made it.
