### ISSUE TITLE
Auto Installer Breaks

### ISSUE THREAD

**Issue by Pogogo007** [babgozd/camporter96-custom#20]
When using the auto installer it opens for a sec then instantly closes without installing the grids. I managed to get what it spews out.
Traceback (most recent call last):
  File "CustomGrids.py", line 63, in <module>
  File "CustomGrids.py", line 47, in pic_download
  File "CustomGrids.py", line 27, in get_file_list
  File "site-packages\valve_keyvalues_python\keyvalues.py", line 44, in __init__
  File "site-packages\valve_keyvalues_python\keyvalues.py", line 181, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/Steam/userdata\\0/config/localconfig.vdf'
[4204] Failed to execute script CustomGrids

**Comment by djandDK** [comment]
are you using the latest version: https://github.com/babgozd/camporter96-custom/releases/latest ?

**Comment by Pogogo007** [comment]
Yes i am

**Comment by djandDK** [comment]
can i get you to tell me which folders are in the C:/Program Files (x86)/Steam/userdata directory?

**Comment by Pogogo007** [comment]
0
16160799
178261714

**Comment by djandDK** [comment]
did you create the 0 folder yourself?

**Comment by Pogogo007** [comment]
no

**Comment by Pogogo007** [comment]
i moved the 0 folder out and the installer works fine afterwards

**Comment by djandDK** [comment]
![image](https://user-images.githubusercontent.com/15907505/65390465-7f5ddc00-dd5f-11e9-9006-529f6e08048c.png)
I have edited the script to help with this error in the future.

**Comment by Pogogo007** [comment]
ok

**Comment by djandDK** [comment]
Should be fixed in #21 so this can be closed now
