### ISSUE TITLE
Python Error - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by wadforth** [babgozd/camporter96-custom#5]
![image](https://user-images.githubusercontent.com/45768489/65316712-5dfbc500-db92-11e9-833d-ac80465a3244.png)

I'm not familiar with Python, so apologies if its obvious.
I assume requests was installed correctly?

![image](https://user-images.githubusercontent.com/45768489/65316914-b92db780-db92-11e9-8fe7-671b1a5cfa45.png)

**Comment by babgozd** [comment]
I am not the coder of python script, it's @ithg so lets call him.

Only thing I noticed was script doesn't work unless config/grid folders created under Steam/userdata/STEAMID folder. Other than that perfectly works for me.

**Comment by ithg** [comment]
check it.
This may be that there are files in your grid folder that are not under the repository, so when the file list is compared, files that are not in the repository will be downloaded from the repository.I will try to fix it.

**Comment by ithg** [comment]
> I am not the coder of python script, it's @ithg so lets call him.
> 
> Only thing I noticed was script doesn't work unless config/grid folders created under Steam/userdata/STEAMID folder. Other than that perfectly works for me.

”config/grid“,is the folder not automatically generated by steam?I found it when I first tried to put the pics in it.

**Comment by babgozd** [comment]
> 
> 
> > I am not the coder of python script, it's @ithg so lets call him.
> > Only thing I noticed was script doesn't work unless config/grid folders created under Steam/userdata/STEAMID folder. Other than that perfectly works for me.
> 
> ”config/grid“,is the folder not automatically generated by steam?I found it when I first tried to put the pics in it.

Steam doesn't create that folder unless user change any artwork for any game.

**Comment by babgozd** [comment]
> 
> 
> check it.
> This may be that there are files in your grid folder that are not under the repository, so when the file list is compared, files that are not in the repository will be downloaded from the repository.I will try to fix it.

Yeah I deleted readme.md in that folder. Also I am gonna remove alternative versions to reduce folder size.

**Comment by wadforth** [comment]
Yeah, so I cleared my grid folder and ran it again, seems to work. :^)

**Comment by ithg** [comment]
fix #6

**Comment by ithg** [comment]
> Yeah, so I cleared my grid folder and ran it again, seems to work. :^)
> Although, some artwork that is in the repo doesn't get applied. Unsure why.
> 
> AC: Odyssey and GTA III didn't get applied from what I can see so far - the IDs are correct so don't know. I did receive the same error at the end.
> 
> Edit 1: Then trying to run the script again, without deleting the contents gets the same error.
> 
> Edit 2: Ran the script multiple times, I got the error at different points. Sometimes it can add 20 images then give the error, the next it could add 60 images then give the error. Seems to not be doing them all.
> 
> Edit 3: After running it 5 times, all images seem to applied. :')

Repository reset just a moment age,so maybe have some problem.If appearing again,plz report.

**Comment by babgozd** [comment]
@ithg I have changed "Ready to use" folder to "grid" and edited the script. I hope everything is working.

**Comment by wadforth** [comment]
Can confirm the new script works without any errors. :)

**Comment by babgozd** [comment]
So do I. Thanks @ithg for amazing efforts. I am gonna write a nice usage tutorial now.

**Comment by ithg** [comment]
> So do I. Thanks @ithg for amazing efforts. I am gonna write a nice usage tutorial now.

My pleasure. :)

**Comment by ithg** [comment]
> So do I. Thanks @ithg for amazing efforts. I am gonna write a nice usage tutorial now.

We can packag the python to .exe,maybe this is better way rather than download python and configuration environment.
